# Generated by Django 4.2.2 on 2023-06-13 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_country', models.CharField(max_length=60)),
                ('start_city', models.CharField(max_length=60)),
                ('start_airport', models.CharField(max_length=100)),
                ('end_country', models.CharField(max_length=60)),
                ('end_city', models.CharField(max_length=60)),
                ('end_airport', models.CharField(max_length=100)),
                ('date_and_time_of_take_off', models.DateTimeField()),
                ('date_and_time_of_arrival', models.DateTimeField()),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
    ]
