# Generated by Django 4.2.2 on 2023-06-14 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_rename_tickets_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='price',
            field=models.FloatField(default=0.0),
        ),
    ]
