# Generated by Django 4.2.2 on 2023-06-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='euro', max_length=10),
        ),
    ]
