# Generated by Django 4.2.2 on 2023-06-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_ticket_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='place_in_plane',
            field=models.IntegerField(default=0),
        ),
    ]
