# Generated by Django 4.2.2 on 2023-06-17 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
