# Generated by Django 4.2.2 on 2023-06-26 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_purchasedticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='currency',
            field=models.CharField(default='EUR', max_length=10),
        ),
    ]
