# Generated by Django 4.2.2 on 2023-06-26 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_alter_ticket_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD - United States Dollar'), ('GBP', 'GBP - British Pound'), ('EUR', 'EUR - Euro'), ('BGN', 'BGN - Bulgarian Lev')], max_length=3),
        ),
    ]
