# Generated by Django 4.2.2 on 2023-06-18 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wallet',
        ),
    ]
