# Generated by Django 4.2.2 on 2023-06-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wallet', '0004_delete_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=30)),
                ('balance', models.FloatField(default=0.0)),
                ('currency', models.CharField(default='euro', max_length=10)),
            ],
        ),
    ]
