# Generated by Django 4.2.2 on 2023-06-18 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0006_remove_wallet_user_name_wallet_user'),
    ]

    operations = [
    ]
