# Generated by Django 4.2.2 on 2023-06-18 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0008_auto_20230618_1135'),
    ]

    operations = [
    ]
